name: CI build

on:
  push:
    branches:
      - 'master'

jobs:
  kylian-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Report React
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: '**/jest-results.xml'
          reporter: jest-junit
          fail-on-empty: 'false'
          fail-on-error: 'true'
